### ISSUE TITLE
Some typography/readability Improvement suggestions

### ISSUE THREAD

**Issue by geoffreycrofte** [alexduloz/superyesmore#7]
Hello Alex,

I was reading an article and I began to edit some CSS. (yeah, that happens xD) I think those lines could help readability, but feel free to evaluate each suggestion.

```css
.article-content blockquote,
.article-content li,
.article-content p {
	line-height: 1.7;
}

.article-content h1 {
	margin-bottom: 1em;
}

.article-content h2,
.article-content h3 {
	margin-bottom: .75em;
}

.article-content ul,
.article-content ol {
	padding-left: 2.5em;
}

.article-content blockquote p {
	font-size: 28px;
}

.article-content blockquote p:last-child {
	margin-bottom: 0;
}

.article-content li + li {
	margin-top: .875em;
}

.article-content a {
	text-decoration: underline;
}
```

Thanks a lot :)
